apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: apr7-objectdetection-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr7-objectdetection-1
  name: apr7-objectdetection-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
